// Code generated by go-bindata.
// sources:
// public/auth.html
// DO NOT EDIT!

package authproxy

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _publicAuthHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\x90\x41\x4b\xc3\x40\x10\x85\xef\xfe\x8a\x69\x0f\x7a\x29\xdd\x62\x8d\xd4\xb0\x49\x11\x0f\xea\x4d\xbc\x78\x94\x4d\x76\xb2\x3b\x74\x92\x09\x9b\x09\x52\x7f\xbd\xac\x11\x11\xbc\xcc\x7c\x03\x6f\xe0\xbd\x67\xa3\xf6\x5c\x5f\x00\xd8\x88\xce\x7f\x83\xf9\xa5\x46\xfc\x39\x03\x80\x1d\x97\x0d\xf0\x86\xcc\x1b\x88\xc8\x2c\xa0\x11\x13\xae\x16\x81\x19\xff\x2b\xaf\x12\x42\x10\x1a\x02\xa8\xc0\x20\x1f\xa0\x8e\x4f\x99\x35\x22\x3c\x92\x3e\xcd\x0d\xdc\xbf\x3c\x6f\xe1\x15\x9d\x3f\x1f\x7f\xfe\xac\x83\x98\xb0\xab\xd6\x51\x75\x9c\x4a\x63\x02\x69\x9c\x9b\x6d\x2b\xbd\x61\x09\x34\x18\x71\xb3\x46\x93\x87\x24\xfa\xc4\xe3\xd4\xca\x88\xd5\x3c\x61\x2a\xb1\x77\xc4\x9b\x84\xce\x97\x92\xc2\x65\xcb\x84\x83\xbe\x93\xaf\x6e\x6f\x76\xd7\x87\x5d\xe7\x0e\x5d\x87\xbe\x28\x8a\xfd\xfe\xae\x59\xd7\x0f\x4c\xed\x09\x72\x0c\x6b\x5c\x9d\xad\x35\x18\x68\x58\xe5\xeb\x6f\x2e\x6b\x96\x2e\xac\x59\xfa\xfa\x0a\x00\x00\xff\xff\x96\x2a\xcc\x64\x37\x01\x00\x00")

func publicAuthHtmlBytes() ([]byte, error) {
	return bindataRead(
		_publicAuthHtml,
		"public/auth.html",
	)
}

func publicAuthHtml() (*asset, error) {
	bytes, err := publicAuthHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "public/auth.html", size: 311, mode: os.FileMode(420), modTime: time.Unix(1501733404, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"public/auth.html": publicAuthHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"public": &bintree{nil, map[string]*bintree{
		"auth.html": &bintree{publicAuthHtml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
